spring:
  application:
    name: resource-allocation-management
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/resource_allocation}
    username: ${SPRING_DATASOURCE_USERNAME:rams}
    password: ${SPRING_DATASOURCE_PASSWORD:rams_password}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null
  sql:
    init:
      mode: always

server:
  port: ${SERVER_PORT:8081}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.example.rams: INFO
